language: java

sudo: required

notifications:
email: james.hn.sears@gmail.com

services:
  - docker

addons:
  sonarcloud:
    organization: "jameshnsears-github"
    token:
      secure: "cPJobe6rfyXk6zC769fm+eI2xL95nJ498Pwg0DPbpJJg1iPlkn36wXmr0EvBkigWWrAZ7kNbuzA2Dc0Py8S6M8DKsEfMuAt+sw0ggu8CWKxX429xmKHXCHKaU9nb3WxrqqDyMlmHV0yF3mXhopYWX0kn5EwiXiYQt1XMYsRjlEx1sTr030p8f0btFVR+ZVvschmZ6fHt6deXXh0EBHMrJsRPm3VQKBUGdqVa8LO9JbgpE+mpnrcCPlR63WTzqEmB4vavNadCcHx+tLDt90NVQWod6jWlEhwtAmn2AkHw57adYZcaTWS5J8YKGmVHWx6WLLxXgakKyBlNOZM9WbErQyT/UisVVWL50/08k8YobveO+xxnFIZ7NNOA4uSFC8TjXX6cWOFukA7nyKCF+Gvib/solG3V2vL0cNX6rlkb6zAUOrVw9Il0pTX5n65QaRuJhtPxKhEhbHJkIKAJWWj/2jVf9ENbbRL8b5V2K9JwYzDh2Jgy2ZvCzPRQwiqraoWC6sPIjrgtql56Y4wgLu7L0bowFbNotJypeivWTPtS/9kjTjNHT54GkfsPBflS+ZR4EhMxyxWmqbUGdVKgCaZ7/kf41Nz5jjdwJFCceQpN2aw3gEJXp/ReR+A3eCwOWsUQNJIXBD+sU3A1aH7ozKfO2EQlE4xOIJ8eeAWrFsIP8A8="

env:
  global:
    - secure: "Ys34LcqC766CU7aVeLt0QBpGE4PIuVDKcgsi0CND4T514c1ghjf3CozZxhpXUPX8dbb76z/tiFt3/05DWn1GY5D5W2cOoM0IZ/emjSAfukeIDVEjORl6b3V7CfoXOsa1dpGVpeE6OANCEckLavuFDJBOARIlzbwC9FDW0AE8CnSynZvEo3Vb7luYD7yJncL/twGs7xe/owDFtqCivw26B1+AwyhqlMNPrTmIhG3a+mh0FAiKhYkbyVKqE2xjDbnB7SzgnkJPRn6b5/IgO3tHdc7NK6xuAvrNDq9CDRMluI4ABd5n98YwYIU5qoBLxHUAHimOv+YOF0mJaBuTZrzFTZaqr8GANlywvqtMtrqSA9HlBr2DHD2d6yDnelmoiZay7+WXZsiWFAK0mboeCzZoB3Dy38CUYe1X9kwyAfWEGSyROfuo7eXAPIhoz2UW/Ue/Xxz065k6V50maSxMRiCQ1EDrMvHX9au9m5Rrfhnl+pC5m/vek1Yzkbivrwv3O4/ckJvjyGluuLbiop24BkebniXm6C2/z/AS1UNgAJWw75jpvo/3vSE4+CIX1B/XjLkTe5FLULePaa4qs6CJt1T7A4Wc2El2lEjtLQDWmTqcHVN2P/52js0NND2DEpvu/agCvn6r1xxo6dgX2dj65FFu9DF4cPe+xmw6nKuTU97FdUE="

jdk:
  - openjdk10

cache:
  directories:
  - $HOME/.m2
  - $HOME/.sonar/cache

script:
  - mvn clean test jacoco:report org.eluder.coveralls:coveralls-maven-plugin:report
  - mvn checkstyle:check spotbugs:check pmd:pmd
  - sonar-scanner
