language: java

sudo: required

notifications:
email: james.hn.sears@gmail.com

services:
  - docker

addons:
  sonarcloud:
    organization: "jameshnsears-github"
    token:
      secure: "dWBy76ouo0BzXZtiwQydmoc2DDBGrcXR1qhgTG0xNdaP2opEFjvrxVH0NtFIwEj2SnS3P2eb4FOIEHa6p5kbdtgkVveZqeZOhm8TOfL9Ty9SncJ3ZCLNaTOm7nyUCVnYIRlDmakuZfyJLh+sFdah2RlFMSPvHqKuOuOaMHGnYeermj+lU06LIhXpGqtVwMCRId+SZ79L5/nOjFL1aiMpj44OWlvYj5BOHzoP1lFqChwPP4U+OlZ0inl6sfVm/KeEIPJlG44QaNKItIMZ1rXAAuTOi5vcvE6oUHAxDKHOLcKo880soCkdhNeLjRmViRPx5+j7nSYcuLe/+plrhE2MBoU+msZTi8nAzrnyt7exK3garh2eQPKZj6cjj0Qf9gBUu8rLDxAmwaeyoqRYJ8cJ4qLgi4b3lGc+w0c6UR6H4bF2+ZKR93HGihudkegLPQKFFecstmmQG2uAh99bwmcOD2r1I4kGt37pdmKg+IscVHwN/s/jKARlDLShASR1pWy6QnfksVZL3CcNLJoe48UHx7gJ3jqpe79mL3RElQ9vPDXrIskoE/HcnXX3nVBmk1R3w1JNvHXhM4i44lZvHkUVNyTF33FjlrhyE/OKynXUXU0jjPKilDUTiMhqws/Nh0xFIGs7R3uS6Ca0KBUGX1AB3ieTPf2rb9wmyBBmSQmthos="

env:
  global:
    - secure: "Ys34LcqC766CU7aVeLt0QBpGE4PIuVDKcgsi0CND4T514c1ghjf3CozZxhpXUPX8dbb76z/tiFt3/05DWn1GY5D5W2cOoM0IZ/emjSAfukeIDVEjORl6b3V7CfoXOsa1dpGVpeE6OANCEckLavuFDJBOARIlzbwC9FDW0AE8CnSynZvEo3Vb7luYD7yJncL/twGs7xe/owDFtqCivw26B1+AwyhqlMNPrTmIhG3a+mh0FAiKhYkbyVKqE2xjDbnB7SzgnkJPRn6b5/IgO3tHdc7NK6xuAvrNDq9CDRMluI4ABd5n98YwYIU5qoBLxHUAHimOv+YOF0mJaBuTZrzFTZaqr8GANlywvqtMtrqSA9HlBr2DHD2d6yDnelmoiZay7+WXZsiWFAK0mboeCzZoB3Dy38CUYe1X9kwyAfWEGSyROfuo7eXAPIhoz2UW/Ue/Xxz065k6V50maSxMRiCQ1EDrMvHX9au9m5Rrfhnl+pC5m/vek1Yzkbivrwv3O4/ckJvjyGluuLbiop24BkebniXm6C2/z/AS1UNgAJWw75jpvo/3vSE4+CIX1B/XjLkTe5FLULePaa4qs6CJt1T7A4Wc2El2lEjtLQDWmTqcHVN2P/52js0NND2DEpvu/agCvn6r1xxo6dgX2dj65FFu9DF4cPe+xmw6nKuTU97FdUE="

jdk:
  - openjdk10

cache:
  directories:
  - $HOME/.m2
  - $HOME/.sonar/cache

script:
  - mvn clean test jacoco:report org.eluder.coveralls:coveralls-maven-plugin:report
  - mvn checkstyle:check spotbugs:check pmd:pmd
  - sonar-scanner
