language: java

sudo: required

notifications:
email: james.hn.sears@gmail.com

services:
  - docker

jdk:
  - oraclejdk11

cache:
  directories:
  - $HOME/.m2

before_script:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - mvn clean
  - mvn test
  - mvn checkstyle:check
  - mvn spotbugs:check

after_success:
  - mvn jacoco:report coveralls:report
