language: java

sudo: required

notifications:
email: james.hn.sears@gmail.com

services:
  - docker

jdk:
  - oraclejdk11

cache:
  directories:
  - $HOME/.m2

before_script:
  - mvn install -Dpmd.skip=true -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - mvn clean test checkstyle:check spotbugs:check pmd:cpd-check
  # - mvn pmd:pmd-check

after_success:
  - mvn  coveralls:report
