language: java

sudo: required

notifications:
email: james.hn.sears@gmail.com

services:
  - docker

jdk:
  - oraclejdk11

cache:
  directories:
  - $HOME/.m2

script:
  - mvn clean
  - mvn checkstyle:check
  - mvn spotbugs:check
  - mvn test

after_success:
  - mvn jacoco:report coveralls:report
