language: java

sudo: required

notifications:
email: james.hn.sears@gmail.com

services:
  - docker

jdk:
  - oraclejdk11

cache:
  directories:
  - $HOME/.m2

script:
  - mvn clean test checkstyle:check spotbugs:check pmd:cpd-check

after_success:
  - mvn coveralls:report
