language: java

sudo: required

notifications:
email: james.hn.sears@gmail.com

services:
  - docker

jdk:
  - oraclejdk10
  - oraclejdk11

cache:
  directories:
  - $HOME/.m2

script:
  - mvn clean checkstyle:check spotbugs:check test

after_success:
  - mvn jacoco:report coveralls:report
